import { Inter } from "next/font/google";
import { Links } from '@/app/ui/nav-link'; // Correction du nom du composant
import "./styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Links /> {/* Utilisation du bon nom de composant */}
        <main>{children}</main>
        </body>
        </html>
    );
}
